export type PermissionLevel = "L0" | "L1" | "L2" | "L3" | "L4";

export type ServiceId =
  | "assets"
  | "invest"
  | "planning"
  | "tax"
  | "insurance"
  | "loan"
  | "spending"
  | "assistant"
  | "agent"
  | "risk"
  | "news"
  | "business"
  | "contract"
  | "global"
  | "voice"
  | "credit"
  | "life";

export type ServiceDefinition = {
  id: ServiceId;
  index: number;
  short: string;
  title: string;
  expert: string;
  description: string;
  accent: string;
  features: string[];
  inputLabel: string;
  inputHint: string;
  defaultValue: number;
  unit: string;
  action: string;
  permission: PermissionLevel;
};

export const permissionCopy: Record<
  PermissionLevel,
  { label: string; description: string }
> = {
  L0: { label: "조회", description: "연결된 데이터를 읽기만 합니다." },
  L1: { label: "분석", description: "계산과 위험 진단을 수행합니다." },
  L2: { label: "추천", description: "대안과 우선순위를 제안합니다." },
  L3: { label: "신청 준비", description: "제출 전 단계까지 자동 작성합니다." },
  L4: { label: "인증 실행", description: "기관 인증 후 샌드박스에서 실행합니다." },
};

export const services: ServiceDefinition[] = [
  {
    id: "assets",
    index: 1,
    short: "NW",
    title: "자산 통합 관리",
    expert: "Net Worth AI",
    description: "금융·실물·디지털 자산과 부채를 하나의 순자산으로 통합합니다.",
    accent: "#00d39b",
    features: [
      "모든 금융계좌 통합",
      "모든 은행 계좌",
      "모든 증권 계좌",
      "모든 카드",
      "모든 보험",
      "연금",
      "ISA",
      "IRP",
      "CMA",
      "예금",
      "적금",
      "외화 계좌",
      "가상자산 거래소",
      "해외 증권",
      "부동산",
      "자동차",
      "금·은",
      "NFT(지원되는 경우)",
      "개인 대출",
      "기업 계좌",
      "실시간 순자산 계산",
    ],
    inputLabel: "추가 자산 평가액",
    inputHint: "수기 자산 또는 새로 연결할 자산의 현재 평가액",
    defaultValue: 30000000,
    unit: "원",
    action: "자산 연결 계획에 추가",
    permission: "L0",
  },
  {
    id: "invest",
    index: 2,
    short: "IV",
    title: "AI 투자 매니저",
    expert: "Portfolio AI",
    description: "포트폴리오를 진단하고 목표·위험에 맞는 전략을 시뮬레이션합니다.",
    accent: "#7c8cff",
    features: [
      "포트폴리오 분석",
      "AI 종목 발굴",
      "ETF 추천",
      "채권 추천",
      "배당 전략",
      "성장주 분석",
      "가치주 분석",
      "리스크 분석",
      "자동 리밸런싱",
      "목표 수익률 관리",
      "손실 제한 전략",
      "시장 사이클 분석",
      "AI 퀀트 전략",
      "백테스트",
      "시나리오 분석",
      "옵션 전략(지원 환경에서)",
      "선물 전략(지원 환경에서)",
      "환율 영향 분석",
    ],
    inputLabel: "분석 대상 투자금",
    inputHint: "현재 운용 중이거나 새로 배분할 금액",
    defaultValue: 50000000,
    unit: "원",
    action: "리밸런싱 승인 요청",
    permission: "L4",
  },
  {
    id: "planning",
    index: 3,
    short: "FP",
    title: "AI 재무설계(CFP)",
    expert: "Life Planner AI",
    description: "생애 목표를 현금흐름과 연결해 월별 실행 계획으로 바꿉니다.",
    accent: "#b681ff",
    features: [
      "은퇴 계획",
      "결혼 자금",
      "주택 구매",
      "자동차 구매",
      "여행 자금",
      "자녀 교육비",
      "창업 자금",
      "유학 자금",
      "월 저축 계획",
      "소비 최적화",
      "현금흐름 분석",
      "목표 달성 시뮬레이션",
    ],
    inputLabel: "목표 금액",
    inputHint: "달성하려는 목표의 미래 필요 금액",
    defaultValue: 300000000,
    unit: "원",
    action: "월 자동저축 계획 만들기",
    permission: "L3",
  },
  {
    id: "tax",
    index: 4,
    short: "TX",
    title: "AI 세금 전문가",
    expert: "Tax Copilot AI",
    description: "세금 영향을 사전에 계산하고 신고 준비 체크리스트를 만듭니다.",
    accent: "#4ea7ff",
    features: [
      "절세 전략",
      "연말정산 준비",
      "양도소득세 추정",
      "종합소득세 추정",
      "증여세 시뮬레이션",
      "상속세 시뮬레이션",
      "해외투자 세금 계산",
      "배당소득세 분석",
      "세금 신고 지원",
    ],
    inputLabel: "과세 대상 예상금액",
    inputHint: "소득·차익·증여 등 계산 기준 금액",
    defaultValue: 30000000,
    unit: "원",
    action: "신고 준비 체크리스트 생성",
    permission: "L3",
  },
  {
    id: "insurance",
    index: 5,
    short: "IN",
    title: "AI 보험 전문가",
    expert: "Coverage AI",
    description: "가입 계약을 읽고 중복·부족·보장 공백을 함께 진단합니다.",
    accent: "#00b8d9",
    features: [
      "보험 분석",
      "중복 가입 탐지",
      "부족한 보장 분석",
      "보험료 절감 제안",
      "갱신 시기 관리",
      "보험금 청구 지원",
      "보장 공백 분석",
      "자동차 보험 비교",
      "실손보험 분석",
    ],
    inputLabel: "필요 보장액",
    inputHint: "가구 소득과 부채를 고려한 목표 보장액",
    defaultValue: 200000000,
    unit: "원",
    action: "보장 개선안 비교 요청",
    permission: "L3",
  },
  {
    id: "loan",
    index: 6,
    short: "LN",
    title: "AI 대출 전문가",
    expert: "Debt AI",
    description: "금리·상환·신용을 함께 계산해 부채 비용을 낮춥니다.",
    accent: "#ffb454",
    features: [
      "최저 금리 탐색",
      "대환대출 추천",
      "상환 계획",
      "신용점수 관리",
      "대출 가능 금액 추정",
      "금리 변동 분석",
      "조기 상환 시뮬레이션",
    ],
    inputLabel: "대출 잔액",
    inputHint: "상환 또는 대환을 검토할 현재 원금",
    defaultValue: 120000000,
    unit: "원",
    action: "대환 사전심사 준비",
    permission: "L3",
  },
  {
    id: "spending",
    index: 7,
    short: "SP",
    title: "AI 소비 관리",
    expert: "Spending AI",
    description: "지출을 자동 분류하고 목표를 해치지 않는 안심 예산을 제시합니다.",
    accent: "#ff8aa5",
    features: [
      "자동 가계부",
      "소비 패턴 분석",
      "예산 관리",
      "구독 관리",
      "카드 추천",
      "캐시백 최적화",
      "포인트 관리",
      "마일리지 관리",
      "소비 습관 개선",
    ],
    inputLabel: "이번 달 소비 예산",
    inputHint: "고정비를 제외하고 관리할 월간 금액",
    defaultValue: 2400000,
    unit: "원",
    action: "예산 규칙 적용",
    permission: "L3",
  },
  {
    id: "assistant",
    index: 8,
    short: "FA",
    title: "AI 금융 비서",
    expert: "FIA Supervisor",
    description: "한 문장을 여러 금융 전문가의 실행 가능한 작업으로 분해합니다.",
    accent: "#6fe3ff",
    features: [
      "자연어 금융 상담",
      "여행 예산 계산",
      "카드 추천",
      "환전 계획",
      "여행보험 비교",
      "숙소 할인 탐색",
      "귀국 후 정산",
    ],
    inputLabel: "예상 여행비",
    inputHint: "여행 또는 복합 금융 질문의 기준 금액",
    defaultValue: 3500000,
    unit: "원",
    action: "전체 여행 플랜 승인",
    permission: "L3",
  },
  {
    id: "agent",
    index: 9,
    short: "AG",
    title: "AI 자동 실행(Agent)",
    expert: "Action Agent",
    description: "사용자가 정한 범위 안에서 금융 행동을 예약하고 샌드박스 실행합니다.",
    accent: "#00e0b8",
    features: [
      "자동 송금",
      "자동 저축",
      "자동 투자",
      "자동 환전",
      "자동 공과금 납부",
      "자동 리밸런싱",
      "자동 대출 상환",
      "자동 카드 결제",
      "자동 구독 해지",
    ],
    inputLabel: "1회 실행 한도",
    inputHint: "기관 인증 전에 허용할 최대 샌드박스 금액",
    defaultValue: 1000000,
    unit: "원",
    action: "샌드박스 실행 승인",
    permission: "L4",
  },
  {
    id: "risk",
    index: 10,
    short: "RK",
    title: "AI 위험관리",
    expert: "Guardian AI",
    description: "거래·메시지·접속 신호를 결합해 금융 위험을 조기에 경고합니다.",
    accent: "#ff625f",
    features: [
      "이상 거래 탐지",
      "피싱 탐지",
      "스미싱 탐지",
      "보이스피싱 위험 경고",
      "계좌 탈취 의심 감지",
      "신용카드 도난 탐지",
      "투자 사기 탐지",
      "개인정보 유출 모니터링",
      "신용점수 변화 감시",
    ],
    inputLabel: "의심 거래 금액",
    inputHint: "위험 점수를 계산할 거래 또는 노출 금액",
    defaultValue: 4800000,
    unit: "원",
    action: "보호 조치 시뮬레이션",
    permission: "L4",
  },
  {
    id: "news",
    index: 11,
    short: "NS",
    title: "AI 금융 뉴스 분석",
    expert: "Market Intel AI",
    description: "뉴스를 요약하고 내 자산에 미치는 영향을 직접 연결합니다.",
    accent: "#e4cf63",
    features: [
      "경제 뉴스 요약",
      "기업 실적 요약",
      "정책 변화 요약",
      "금리 변화 분석",
      "환율 분석",
      "원자재 분석",
      "산업 동향 분석",
      "내 자산 영향 설명",
    ],
    inputLabel: "영향 분석 보유액",
    inputHint: "뉴스 이벤트의 영향을 계산할 관련 자산 금액",
    defaultValue: 40000000,
    unit: "원",
    action: "영향 알림 규칙 저장",
    permission: "L2",
  },
  {
    id: "business",
    index: 12,
    short: "B2",
    title: "AI 기업금융(B2B)",
    expert: "CFO AI",
    description: "법인 자금·매출·비용·재고를 연결해 미래 현금을 예측합니다.",
    accent: "#8ca7c8",
    features: [
      "법인 자금 관리",
      "현금흐름 예측",
      "급여 관리",
      "비용 분석",
      "매출 예측",
      "재고 자금 최적화",
      "투자 계획",
      "CFO 지원",
    ],
    inputLabel: "월 운영비",
    inputHint: "급여·임차료·매입을 포함한 월간 현금 유출",
    defaultValue: 45000000,
    unit: "원",
    action: "자금 집행안 승인 요청",
    permission: "L4",
  },
  {
    id: "contract",
    index: 13,
    short: "CT",
    title: "AI 계약 분석",
    expert: "Document AI",
    description: "금융 문서에서 숨은 비용과 위험 조항을 근거 위치와 함께 찾습니다.",
    accent: "#d6a8ff",
    features: [
      "보험 약관 분석",
      "대출 계약 분석",
      "카드 약관 분석",
      "투자설명서 분석",
      "펀드 설명서 분석",
      "숨겨진 수수료 탐지",
      "위험 조항 요약",
    ],
    inputLabel: "계약 금액",
    inputHint: "수수료와 위험 노출을 환산할 계약 기준금액",
    defaultValue: 25000000,
    unit: "원",
    action: "검토 질문 목록 내보내기",
    permission: "L2",
  },
  {
    id: "global",
    index: 14,
    short: "FX",
    title: "AI 해외 금융",
    expert: "Global Money AI",
    description: "국가·통화·세금·송금 비용을 한 번에 비교합니다.",
    accent: "#52c8ff",
    features: [
      "해외송금 최적 경로",
      "환율 예측",
      "해외 카드 추천",
      "해외 세금 기초 정보",
      "국가별 금융 규정 안내",
      "해외 투자 관리",
    ],
    inputLabel: "환전·송금 예정액",
    inputHint: "수수료와 환율 시나리오를 비교할 원화 금액",
    defaultValue: 10000000,
    unit: "원",
    action: "환전·송금 예약 준비",
    permission: "L3",
  },
  {
    id: "voice",
    index: 15,
    short: "VC",
    title: "AI 음성 금융",
    expert: "Voice Finance AI",
    description: "조회부터 상담까지 음성으로 수행하고 실행 내용은 화면에서 재확인합니다.",
    accent: "#ff9f76",
    features: [
      "음성 송금",
      "음성 투자 지시",
      "음성 조회",
      "음성 예산 관리",
      "음성 금융 상담",
    ],
    inputLabel: "음성 명령 금액",
    inputHint: "화면 재확인이 필요한 음성 실행 기준금액",
    defaultValue: 300000,
    unit: "원",
    action: "음성 명령 재확인",
    permission: "L4",
  },
  {
    id: "credit",
    index: 16,
    short: "CR",
    title: "AI 신용관리",
    expert: "Credit AI",
    description: "점수 변화 원인을 설명하고 개선 행동의 효과를 예측합니다.",
    accent: "#83d67b",
    features: [
      "신용점수 예측",
      "점수 하락 원인 분석",
      "점수 개선 전략",
      "대출 가능성 예측",
    ],
    inputLabel: "줄일 단기부채",
    inputHint: "신용 개선 효과를 계산할 상환 예정 금액",
    defaultValue: 5000000,
    unit: "원",
    action: "신용 개선 루틴 시작",
    permission: "L3",
  },
  {
    id: "life",
    index: 17,
    short: "LF",
    title: "AI 라이프 이벤트 관리",
    expert: "Life Event AI",
    description: "삶의 변화에 필요한 금융 행동을 한 번에 묶어 제안합니다.",
    accent: "#ff78ba",
    features: [
      "취업",
      "이직",
      "결혼",
      "출산",
      "창업",
      "은퇴",
      "상황별 금융 계획 자동 제안",
    ],
    inputLabel: "이벤트 준비자금",
    inputHint: "선택한 생애 이벤트에 배정할 총금액",
    defaultValue: 50000000,
    unit: "원",
    action: "이벤트 실행 로드맵 생성",
    permission: "L3",
  },
];

export const getService = (id: ServiceId) =>
  services.find((service) => service.id === id) ?? services[0];

export const featureCount = services.reduce(
  (count, service) => count + service.features.length,
  0,
);
